### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Mni\FrontYAML\Parser' not found

### ISSUE THREAD

**Issue by jasonbayton** [mnapoli/FrontYAML#12]
Installed this via composer today (cloned repo, not zip) and I can't seem to get past the error shown.

I've tried require_once on index.php, as well as originally config/config.php
The code used to invoke is exactly as depicted in the README.

htaccess rule uses one single index.php and dynamically imports .md file based on URL

Parsedown alone via include of the PHP file works perfectly fine.

**Comment by jasonbayton** [comment]
As I'm sure you would have pointed out, this was a composer issue!

**Comment by mnapoli** [comment]
:+1: happy to know it worked
