### ISSUE TITLE
parser dies on UTF-8 characters

### ISSUE THREAD

**Issue by jhall39** [mnapoli/FrontYAML#14]
Any time there's a character like:
“
or
”
or
’
among others in my markdown text and I parse the file with this library, it dies with an error message of:

`
 PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'The YAML value does not appear to be valid UTF-8.' in vendor/symfony/yaml/Parser.php:88

`

Even though it's happening from those characters in my text. Any way to resolve this other than muting the exceptions? I can manually replace those characters with html entities, but I can't always guarantee that I can catch each one. Trying to use htmlentities() or htmlspecialchars() in php completely breaks the file as well and neither the front-matter nor markdown gets rendered.

**Comment by jhall39** [comment]
Apparently this works if I go into my text editor and tell it to convert to utf-8 instead of ANSI. It'd be nice if the parser didn't totally choke on it if in the wrong format though.

**Comment by mnapoli** [comment]
Hi @jhall39, could you either open a pull request with a failing test or copy the content of a document that causes such issue in here? Thanks
