### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by petk** [mnapoli/FrontYAML#15]
Hello, currently the symfony/yaml component is set to `~2.1|^3.0`. Is there any option to bump it to the upcoming Symfony 4.0 as well?

Thanks.

**Comment by mnapoli** [comment]
Hi, I'll try to get onto that ASAP, feel free also to send a pull request if you want (with the tests we'll see quickly if everything still works ^^).

**Comment by mnapoli** [comment]
Thanks!

**Comment by petk** [comment]
Wow, thanks so much. This is great.
