### ISSUE TITLE
 php version (8.0.0)

### ISSUE THREAD

**Issue by simonproud** [mnapoli/FrontYAML#24]
- Root composer.json requires mnapoli/front-yaml ^1.7 -> satisfiable by mnapoli/front-yaml[1.7.0].
    - mnapoli/front-yaml 1.7.0 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by mnapoli** [comment]
You can't bother to check if a PR exists, you can't bother to format just a little bit the issue, you can't bother to work on a solution. Nobody is working for you here.

Judging by your behavior towards other open-source maintainers (https://github.com/knuckleswtf/scribe/issues/153 and https://github.com/knuckleswtf/scribe/issues/152) I'm blocking you from this repository.
