### ISSUE TITLE
Normalize EOL before splitting for better cross-OS reliability

### ISSUE THREAD

**Issue by Giuseppe-Mazzapica** [mnapoli/FrontYAML#3]
Today I faced an issue with YAML front matter recognization, in short variables defined using front matter were ignored and front matter was rendered just like normal markdown.

After a bit of debugging I realized that problem was that files were generated in Linux, but I was parsing them in Windows.

That caused

```php
$lines = explode(PHP_EOL, $str);
```
in [`Parser.php`](https://github.com/mnapoli/FrontYAML/blob/master/src/Parser.php#L49)

to not properly explode by lines, because in the line above `PHP_EOL` is, of course, evaluated in the system that is parsing, that is not necessarily the system where files were created.

I think that for better cross-OS reliability, before to split string by `PHP_EOL` is a good idea *normalize* end of lines, e.g. by replacing all windows-like and linux-like EOL with `PHP_EOL` in a way that exploding by it will always work as expected.

An alternative would be using `preg_split` with a regex that matches both EOL types.

**Comment by mnapoli** [comment]
Was fixed in #4 :)

**Comment by mnapoli** [comment]
Release 1.3.0
